name: computiq_academy_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.5.1
  lottie: ^1.2.1
  flutter:
    sdk: flutter
  dio: ^4.0.4
  cached_network_image: ^3.2.0
  flutter_svg: ^0.22.0
  get_storage: ^2.0.3
  double_back_to_close_app: ^2.1.0
  http: ^0.13.4
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  youtube_player_flutter: ^8.0.0
  flutter_widget_from_html_core: ^0.8.4
  rounded_expansion_tile: ^0.0.13
  flutter_linkify: ^5.0.2
  flutter_phoenix: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Final-08.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/theme_images/background_image.png
    - assets/images/maxresdefault.jpg
    - assets/images/computiq_images/computiq-login.svg
    - assets/images/Final-08.png
    - assets/images/undraw_no_data_re_kwbl.svg
    - assets/images/icons_images/home.png
    - assets/images/icons_images/scores.png
    - assets/images/icons_images/tasks.png
    - assets/images/lottie_animation/Comutiq AE.json
    - assets/images/placeholder_image.png
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Meteopolis/Metropolis-Black.otf
        - asset: assets/fonts/Meteopolis/Metropolis-BlackItalic.otf
        - asset: assets/fonts/Meteopolis/Metropolis-Bold.otf
        - asset: assets/fonts/Meteopolis/Metropolis-BoldItalic.otf
        - asset: assets/fonts/Meteopolis/Metropolis-ExtraBold.otf
        - asset: assets/fonts/Meteopolis/Metropolis-ExtraBoldItalic.otf
        - asset: assets/fonts/Meteopolis/Metropolis-ExtraLight.otf
        - asset: assets/fonts/Meteopolis/Metropolis-ExtraLightItalic.otf
        - asset: assets/fonts/Meteopolis/Metropolis-Light.otf
        - asset: assets/fonts/Meteopolis/Metropolis-LightItalic.otf
        - asset: assets/fonts/Meteopolis/Metropolis-Medium.otf
        - asset: assets/fonts/Meteopolis/Metropolis-MediumItalic.otf
        - asset: assets/fonts/Meteopolis/Metropolis-Regular.otf
        - asset: assets/fonts/Meteopolis/Metropolis-RegularItalic.otf
        - asset: assets/fonts/Meteopolis/Metropolis-SemiBold.otf
        - asset: assets/fonts/Meteopolis/Metropolis-SemiBoldItalic.otf
        - asset: assets/fonts/Meteopolis/Metropolis-Thin.otf
        - asset: assets/fonts/Meteopolis/Metropolis-ThinItalic.otf
